server:
  port: 8080

spring:
  application:
    name: BTree-Design
  # mysql数据库
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ds-btree?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 2216348784
      initial-size: 10
      max-active: 60
      min-idle: 5
      filters: wall,mergeStat
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
      test-while-idle: true
      test-on-borrow: true
mybatis-plus:
  #配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted
  #sql打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#日志配置
logging:
  level: #配置指定包的路径下应用程序的日志记录和日志级别。
    root: info
    springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator: error
    org.springframework: warn
  file:
    path: \logs\ #设置日志输出路径
    name: book-crud.log #设置日志文件的名称